
version: 2
jobs:
  build:
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: testim/docker-cli
    steps:
      - run: mkdir -p $CIRCLE_TEST_REPORTS/testim/
      - run: testim --token $TestimToken --project $TestimProject --test-plan "circleCI" --parallel 2 --grid "Testim-Grid" --mode selenium --result-label ${CIRCLE_BUILD_NUM} --report-file $CIRCLE_TEST_REPORTS/testim/results.xml --turbo-mode
      - store_artifacts:
          path: /tmp/circleci-test-results
      - store_test_results:
          path: /tmp/circleci-test-results